buildscript {
    ext.minSdkVersion = 23  // Required by flutter_doc_scanner (ML Kit document scanner)
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.0"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

// Custom buildDir configuration removed to fix Flutter APK detection
// rootProject.buildDir = 'C:/temp/gradle-build'
// subprojects {
//     project.buildDir = "${rootProject.buildDir}/${project.name}"
// }

subprojects {
    afterEvaluate {
        if (project.hasProperty('android')) {
            android {
                compileSdkVersion 35
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
